### PR TITLE
Update 02_07_challenge.py

### PR DESCRIPTION
**Pull request by owenwu811**
My edits - drew various different triangles with for loops

### CODE REVIEW

**Comment by respecht** [comment]
Not merging, but it's very nice :) Love the use of the input function!

**Comment by owenwu811** [comment]
Sorry - I'm new to github. I'm trying to figure out how to publish my
changes on github.

**Review by SAYANDIP1 — APPROVED** [review]

**Comment by owenwu811** [comment]
Hi Ryan,

     For Challenge #2, I have a few questions and misunderstandings.

1. Is there a reason you used self.direction = [0,1]? I'm not understanding
where those numbers are coming from or the logic behind them
2. is there a reason you called the variable "radians" in radians =
(degrees/180) * math.pi?
3. I thought forward is supposed to be 4 seperate functions - one for each
direction? Also, how is the forward function - self.pos[0] +
self.direction[0], self.pos[1], self.direction[1] - moving the scribe
forward?
4. I'm not sure why the position arguments are supposed to be integers and
why the round function?


I watched the corresponding lesson on basic data types, but I'm not sure
how we are supposed to get from that course to knowing how to do this? How
do i bridge this knowledge gap?

My code for Challenge #2 - 3-07 is below:

def forwardright(self, direction):
    degrees = TerminalScribe(180.0, 0.0) #is this actually moving the
scribe anywhere? follow directions
    direction = int(cos(degrees/180) * 3.14) # figure out this type error
forwardright()

def forwarddown(self, direction):
    degrees = TerminalScribe(0.0, 180.0)
    direction = int(cos(degrees/180) * 3.14)
forwarddown()
def forwardleft(self, direction):
    degrees = TerminalScribe(0.0, 0.0)
    direction = int(cos(degrees/180) * 3.14)
forwardleft()
def forwardup(self, direction):
    degrees = TerminalScribe(0.0, 0.0)
    direction = int(cos(degrees/180) * 3.14)
forwardup()

# Challenge2: give terminal scribe class a sense of direction. give
direction attribute to constructor so that
# it knows which way it is pointing
# create a function called forward that moves it in that direction
# directions should be any floating point or int number where 0 points
up and 180 points down
# think of directions as two numbers: up down component and left right
component. move that far right and that far down to get
# from point a to point b. These components - up down and left right
give you direction vector
# to convert a number of degrees into this direction vector, you can
use the equation: cos((degrees/180) * pi
# set the direction
# make your scribe move with just that forward function after a direction is set

**Comment by respecht** [comment]
Hi @owenwu811 ! My responses below:

_1. Is there a reason you used self.direction = [0,1]? I'm not understanding
where those numbers are coming from or the logic behind them_

[0, 1] is just a random initial direction, in this case, pointing down. It will get reset to something else by the code later on. The initial direction doesn't really matter.


_2. is there a reason you called the variable "radians" in radians =
(degrees/180) * math.pi?_

Yes, it's because that value represents the number of radians: https://en.wikipedia.org/wiki/Radian 
Radians happen to be very handy when you're trying to figure out how long your unit vectors (https://en.wikipedia.org/wiki/Unit_vector) are while pointed in a particular direction.

_3. I thought forward is supposed to be 4 seperate functions - one for each
direction? Also, how is the forward function - self.pos[0] +
self.direction[0], self.pos[1], self.direction[1] - moving the scribe
forward?_

Nope, you don't need four separate forward functions. Just think about it: Do you, as a person, need a separate mode of walking if you're going North or East or SouthWest? Nope! You just tell your legs "hey, keep going forward in whichever direction I happen to be pointed!" Same thing here. That's why we store the `self.direction` variable as the direction we're currently "pointed in" and then just call the forward function.

Remember, the direction is a unit vector. So when you add a directional unit vector to a position, you move forward by 1 in that direction.

_4. I'm not sure why the position arguments are supposed to be integers and
why the round function?_

Because we're drawing this on a terminal which is used for printing text characters. It's basically ASCII art! There's the "first character," "second character," "third character" -- but you can't draw a character between them. That... doesn't make sense. So when we're drawing on the screen, we need to round the values first.

**Comment by owenwu811** [comment]
Ryan,

     One last question: if I’m struggling with some of these hands on
challenges in your course, meaning I get completely lost on how to get the
scribe to move, and your explanations don’t really spark a connection
meaning I can’t come up with your solution in my own head, does that mean
filling in knowledge gaps by taking as many multiple choice quizzes on
Python in Google and reviewing every missed question until I can get 100%
on new quizzes I have never seen before multiple times? I used this
strategy on standardized tests in school, but I’m not sure if this applies
to becoming a software engineer as well since this is the only strategy I
know of. Is this advisable?

-Owen

**Comment by respecht** [comment]
@owenwu811 My goal with designing challenges was to complement the multiple choice quizzes by "filling in the gaps" of real understanding and problem-solving that quizzes weren't able to do. 
Your time would likely be better spent studying and modifying the challenge code -- maybe even drawing diagrams on paper to understand how it's moving and what the functions are doing. Or, if you're really not inspired by the challenge code problem, come up with your own piece of software and experiment with that!

The "engineering" in "software engineering" isn't a misnomer. It's not just the syntax of the language that you need to learn. You need to be able to model "real world" systems in code, understand how components interact with each other, how to extend and augment systems, and understanding basic principles of physics and mathematics also comes in handy ;) 

Unfortunately, the only way to learn software engineering is by... well, engineering software!

**Comment by jablka** [comment]
hello @respecht,
I am _analyzing_ this first _scribe challenge_, file `02_07_challenge.py`.
and I have a brief question regarding the concept of the grid `Canvas._canvas`.
It is a list of lists. But I wonder, if there is some reason or it is just arbitrary that
the _`first line in terminal`_ does not correspond to the _`first line [first list] in Canvas._canvas grid`_ ? 
In other words: lines in terminal are rather columns in Canvas._canvas grid...
Thank you.
(Btw. the challenges are really challenges... quite hard. :)

**Pull request closed without merging**
